-- 1. DROP EXISTING TABLES IN CASCADE ORDER
DROP TABLE IF EXISTS trips CASCADE;
DROP TABLE IF EXISTS maintenance_logs CASCADE;
DROP TABLE IF EXISTS fuel_expenses CASCADE;
DROP TABLE IF EXISTS vehicles CASCADE;
DROP TABLE IF EXISTS drivers CASCADE;

-- 2. CREATE VEHICLES TABLE
CREATE TABLE vehicles (
    reg_no VARCHAR PRIMARY KEY,
    model VARCHAR NOT NULL,
    type VARCHAR NOT NULL DEFAULT 'Van',
    max_capacity NUMERIC NOT NULL,
    odometer NUMERIC NOT NULL DEFAULT 0,
    status VARCHAR NOT NULL DEFAULT 'Available',
    revenue NUMERIC NOT NULL DEFAULT 0,
    acquisition_cost NUMERIC NOT NULL DEFAULT 35000,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. CREATE DRIVERS TABLE
CREATE TABLE drivers (
    license_number VARCHAR PRIMARY KEY,
    name VARCHAR NOT NULL,
    category VARCHAR NOT NULL,
    expiry_date DATE NOT NULL,
    contact_number VARCHAR NOT NULL,
    safety_score INT NOT NULL DEFAULT 100,
    status VARCHAR NOT NULL DEFAULT 'Available',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. CREATE TRIPS TABLE
CREATE TABLE trips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR NOT NULL,
    destination VARCHAR NOT NULL,
    vehicle_reg VARCHAR REFERENCES vehicles(reg_no) ON DELETE SET NULL,
    driver_license VARCHAR REFERENCES drivers(license_number) ON DELETE SET NULL,
    cargo_weight NUMERIC NOT NULL,
    planned_distance NUMERIC NOT NULL,
    status VARCHAR NOT NULL DEFAULT 'Dispatched',
    lat NUMERIC NOT NULL DEFAULT 21.1702,
    lng NUMERIC NOT NULL DEFAULT 72.8311,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. CREATE MAINTENANCE LOGS TABLE
CREATE TABLE maintenance_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_reg VARCHAR REFERENCES vehicles(reg_no) ON DELETE CASCADE,
    description TEXT NOT NULL,
    cost NUMERIC NOT NULL DEFAULT 0,
    status VARCHAR NOT NULL DEFAULT 'Open',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. CREATE FUEL EXPENSES TABLE
CREATE TABLE fuel_expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_reg VARCHAR REFERENCES vehicles(reg_no) ON DELETE CASCADE,
    liters NUMERIC NOT NULL,
    cost NUMERIC NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. DISABLE RLS ON ALL TABLES TO ENABLE PUBLIC ACCESS FOR DEVELOPMENT
ALTER TABLE vehicles DISABLE ROW LEVEL SECURITY;
ALTER TABLE drivers DISABLE ROW LEVEL SECURITY;
ALTER TABLE trips DISABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE fuel_expenses DISABLE ROW LEVEL SECURITY;

-- 8. SEED BASE DATA
INSERT INTO vehicles (reg_no, model, type, max_capacity, odometer, status, revenue, acquisition_cost) VALUES
('VAN-05', 'Ford Transit Van', 'Van', 500, 12450, 'Available', 4500, 35000),
('TRK-10', 'Volvo FH16 Cargo', 'Heavy Cargo Truck', 15000, 89400, 'Available', 28000, 85000),
('TRK-12', 'Scania R500 Flatbed', 'Heavy Cargo Truck', 12000, 45200, 'In Shop', 12500, 78000),
('VAN-01', 'Mercedes Sprinter', 'Van', 800, 195000, 'Retired', 0, 42000);

INSERT INTO drivers (license_number, name, category, expiry_date, contact_number, safety_score, status) VALUES
('DL-77721', 'Alex Mercer', 'Heavy Commercial', '2028-11-14', '+1 555-0192', 92, 'Available'),
('DL-88843', 'Sarah Connor', 'Heavy Commercial', '2029-04-22', '+1 555-0147', 88, 'Available'),
('DL-99912', 'James Morgan', 'Light Commercial', '2024-03-10', '+1 555-0165', 95, 'Available'),
('DL-55421', 'Marcus Wright', 'Heavy Commercial', '2030-01-15', '+1 555-0183', 61, 'Suspended');

INSERT INTO trips (source, destination, vehicle_reg, driver_license, cargo_weight, planned_distance, status, lat, lng) VALUES
('Terminal Alpha', 'Hub Beta', 'TRK-10', 'DL-77721', 4500, 120, 'Dispatched', 21.1702, 72.8311);

INSERT INTO maintenance_logs (vehicle_reg, description, cost, status) VALUES
('TRK-12', 'Brake Pad Replacement', 650, 'Open');

INSERT INTO fuel_expenses (vehicle_reg, liters, cost) VALUES
('TRK-10', 150, 320);
